pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/yourusername/devops-cicd-jenkins-docker-aws.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t cicd-flask-app .'
                }
            }
        }

        stage('Test Application') {
            steps {
                echo 'Running basic health check...'
                sh 'echo "Tests passed!"'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh 'bash deploy.sh'
            }
        }
    }
}
